CREATE TABLE public.profissionais (
	matricula int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(150) NOT NULL,
	departamento varchar(100) NULL,
	cargo varchar(50) NULL,
	telefone varchar(11) NULL,
	CONSTRAINT profissionais_pkey PRIMARY KEY (matricula)
);

CREATE TABLE public.pacientes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(250) NOT NULL,
	telefone varchar(11) NULL,
	data_nascimento date NULL,
	CONSTRAINT pacientes_pkey PRIMARY KEY (id)
);

CREATE TABLE public.internacao (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	data_entrada timestamp NULL,
	data_saida timestamp NULL,
	diagnostico varchar(500) NULL,
	id_paciente int4 NULL,
	id_medico int4 NULL,
	CONSTRAINT internacao_pkey PRIMARY KEY (id),
	FOREIGN KEY (id_paciente) REFERENCES pacientes (id),
	FOREIGN KEY (id_medico) REFERENCES profissionais (matricula)
);